config/routes.rb
Rails.application.routes.draw do

  root to: 'boards#index'
  resources :tasks
  resources :boards
  devise_for :users
  get "task/board/:id", to: "tasks#new", as: :task_board

end


app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks
  validates :name, :description, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :board
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
  validates :name, :surname, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameter, if: :devise_controller?

  protected

  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :create, :show, :update, :destroy]
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @boards = Board.where(user_id: current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @tasks = Task.where(board_id: @board.id)
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)
    set_user_id
    respond_to do |format|
      if @board.save
        format.html { redirect_to root_path, notice: 'O quadro foi criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      set_user_id
      if @board.update(board_params)
        format.html { redirect_to root_path, notice: 'O quadro foi atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'O quadro foi removido com sucesso.' }
    end
  end

  private

    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name, :description)
    end

    def set_user_id
      @board.user_id = current_user.id
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to root_path
  end

  def new
    @task = Task.new
    @board = Board.find(params[:id])
    @task.board_id = @board.id
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to board_path(@task.board_id), notice: 'A tarefa foi criada com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to board_path(@task.board_id), notice: 'A tarefa foi atualizada com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to board_path(@task.board_id), notice: 'A tarefa foi removida com sucesso.' }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :board_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |form| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control", rows:6%>
  </div>

  <div>
    <%= form.submit texto_da_acao, class:"btn btn-primary btn-block" %>
  </div>
  <br/>
<% end %>

app/views/boards/edit.html.erb
<div class="card form-center center-block">
  <h1 class="title text-center">Atualizar quadro</h1>

  <%= render partial: 'form', locals: {texto_da_acao: "Atualizar"}%>

  <%= link_to 'Voltar', boards_path, class:"btn btn-success btn-block" %>
</div>

app/views/boards/index.html.erb
<div class="container">

  <h1 class="text-center title">Quadros</h1>

  <%= link_to 'Criar novo quadro', new_board_path, class: "btn btn-primary"%>
  <br/>
  <%= div_for @boards, class:"col-md-4" do |board|%>
    <div class="row">
      <div class="card">
        <div class="link">
          <%= link_to 'Atualizar', edit_board_path(board), class: "edit" %>
          <%= link_to board, method: :delete, data: { confirm: "Tem certeza que deseja remover #{board.name}?" }, class: "destroy" do%>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
            </svg>
          <% end %>
        </div>
        <%= link_to board, class: "show" do %>
          <%= board.name %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/boards/new.html.erb
<div class="card form-center center-block">
  <h1 class="title text-center">Novo quadro</h1>

  <%= render partial: 'form', locals: {texto_da_acao: "Salvar"}%>

  <%= link_to 'Voltar', boards_path, class:"btn btn-success btn-block" %>
</div>

app/views/boards/show.html.erb
<div class="container">

  <h2 class="text-center title"><%= @board.name %></h2>
  <p class="text-center"><%= @board.description %></p>

  <%= link_to 'Voltar', boards_path, class: "btn btn-success"%>
  <%= link_to 'Criar uma tarefa', task_board_path(@board), class: "btn btn-primary"%>
  <br/>

  <%= div_for @tasks, class:"col-md-4" do |task|%>
    <div class="row">
      <div class="card">
        <div class="link">
          <%= link_to 'Atualizar', edit_task_path(task), class: "edit" %>
          <%= link_to task, method: :delete, data: { confirm: "Tem certeza que deseja remover?" }, class: "destroy" do%>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
            </svg>
          <% end %>
        </div>
        <br/>
        <p><%= task.description %></p>
      </div>
    </div>
  <% end %>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projetoibc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <%= nav_bar brand: "Home", brand_link: root_url do %>
          <%= menu_group do %>
            <%= menu_item "Perfil", user_registration_path, method: :patch %>
          <% end %>
          <%= menu_group do %>
            <%= menu_item "Sair", destroy_user_session_path, method: :delete%>
          <% end %>
        <% end %>
      <% end %>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Descrição" %>
    <%= form.text_area :description, class:"form-control", rows:6 %>
  </div>

  <div >
    <%= form.hidden_field :board_id%>
  </div>

  <div>
    <%= form.submit texto_da_acao, class:"btn btn-primary btn-block" %>
  </div>
  <br/>
<% end %>

app/views/tasks/edit.html.erb
<div class="card form-center center-block">
  <h1 class="title text-center">Atualizar tarefa</h1>

  <%= render partial: 'form', locals: {texto_da_acao: "Atualizar"}%>

  <%= link_to 'Voltar', board_path(@task.board_id), class:"btn btn-success btn-block" %>
</div>

app/views/tasks/new.html.erb
<div class="card form-center center-block">
  <h1 class="title text-center">Novo tarefa</h1>

  <%= render partial: 'form', locals: {texto_da_acao: "Salvar"}%>

  <%= link_to 'Voltar', board_path(@task.board_id), class:"btn btn-success btn-block" %>
  <br/>
</div>